# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ea92baf2d1416c1438cb71aa06d3099ae3c2c2afc49f7ddb8be62db2d404d7af962f1420c945417d0532a8dd21b3b9967b1d33e9344fabfc27b783305861731

test:
  secret_key_base: 1e22fff649157c52c43594f4e5853015a3f07ae8cc41ffcfae01f8cac333919dec1d53d378467160cb71746cd727f0a64a4c8e734a0674ef37b5c26cf2a47799

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
